version: '3.8'

services:
  whatsapp-service:
    build: .
    container_name: whatsapp-baileys
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./sessions:/usr/src/app/sessions
    environment:
      - PORT=3000
